name = "Cockpack"
author = "jan"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc0ecdc1ce751e7f201038a05e71cdfade72cbc50335afa9119c4c40d63765a8"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
