name = "Cockpack"
author = "jan"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee427f0f1b23d86a9d9bce8183b62e2286aa009a63a34f92c882e550bbdd820b"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
