name = "Cockpack"
author = "jan"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06e5f9ea8c6c1bb3878cb18ee6bce129f1f29d047422252d4054e24c7a0bcd09"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
