name = "Cockpack"
author = "jan"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5e7bdde86d300bcc0ed749754b821bdd64de1a49609b237b4d14048c5e1ca3c"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
