name = "Cockpack"
author = "jan"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ada36343d3503b7b5650268280d0ceabb6ca228b336c1fb84f2c5d28cc35d188"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
