name = "Cockpack"
author = "jan"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9a71b8f4417ff0bc1d3dba8ba75596c8af98a2a2b9bfb94fab9df70d626ffa0"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
