name = "AttributeFix"
filename = "AttributeFix-1.12.2-1.0.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2810/157/AttributeFix-1.12.2-1.0.10.jar"
hash-format = "murmur2"
hash = "700332151"

[update]
[update.curseforge]
file-id = 2810157
project-id = 280510
