name = "Blockcraftery"
filename = "blockcraftery-1.12.2-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2716/712/blockcraftery-1.12.2-1.3.1.jar"
hash-format = "murmur2"
hash = "1630431775"

[update]
[update.curseforge]
file-id = 2716712
project-id = 278882
