name = "Buildcraft"
filename = "buildcraft-all-7.99.24.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3204/475/buildcraft-all-7.99.24.8.jar"
hash-format = "murmur2"
hash = "645843516"

[update]
[update.curseforge]
file-id = 3204475
project-id = 61811
