name = "Chicken Chunks 1.8.+"
filename = "ChickenChunks-1.12.2-2.4.2.74-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2755/785/ChickenChunks-1.12.2-2.4.2.74-universal.jar"
hash-format = "murmur2"
hash = "3338398801"

[update]
[update.curseforge]
file-id = 2755785
project-id = 243883
