name = "Chisels & Bits - For Forge"
filename = "chiselsandbits-14.33.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2720/655/chiselsandbits-14.33.jar"
hash-format = "murmur2"
hash = "3211462819"

[update]
[update.curseforge]
file-id = 2720655
project-id = 231095
