name = "Clumps"
filename = "Clumps-3.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2666/198/Clumps-3.1.2.jar"
hash-format = "murmur2"
hash = "1290884162"

[update]
[update.curseforge]
file-id = 2666198
project-id = 256717
