name = "Draconic Evolution"
filename = "Draconic-Evolution-1.12.2-2.3.28.354-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3431/261/Draconic-Evolution-1.12.2-2.3.28.354-universal.jar"
hash-format = "murmur2"
hash = "3391923374"

[update]
[update.curseforge]
file-id = 3431261
project-id = 223565
