name = "Draconic Additions"
filename = "Draconic-Additions-1.12.2-1.17.0.45-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3514/704/Draconic-Additions-1.12.2-1.17.0.45-universal.jar"
hash-format = "murmur2"
hash = "14240401"

[update]
[update.curseforge]
file-id = 3514704
project-id = 314515
