name = "Extra Rails"
filename = "ExtraRails-1.12-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2441/517/ExtraRails-1.12-1.3.0.jar"
hash-format = "murmur2"
hash = "2452788752"

[update]
[update.curseforge]
file-id = 2441517
project-id = 247665
