name = "Fast Leaf Decay"
filename = "FastLeafDecay-v14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2463/272/FastLeafDecay-v14.jar"
hash-format = "murmur2"
hash = "1940914729"

[update]
[update.curseforge]
file-id = 2463272
project-id = 230976
