name = "FastFurnace"
filename = "FastFurnace-1.12.2-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2706/111/FastFurnace-1.12.2-1.3.1.jar"
hash-format = "murmur2"
hash = "1142134081"

[update]
[update.curseforge]
file-id = 2706111
project-id = 299540
