name = "ForgeEndertech"
filename = "ForgeEndertech-1.12.2-4.5.6.0-build.0619.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3505/633/ForgeEndertech-1.12.2-4.5.6.0-build.0619.jar"
hash-format = "murmur2"
hash = "2205825910"

[update]
[update.curseforge]
file-id = 3505633
project-id = 244844
