name = "General Layman's Aesthetic Spying Screen (GLASS)"
filename = "GeneralLaymansAestheticSpyingScreen-1.12.2-7.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2501/251/GeneralLaymansAestheticSpyingScreen-1.12.2-7.0.0.jar"
hash-format = "murmur2"
hash = "882928356"

[update]
[update.curseforge]
file-id = 2501251
project-id = 282164
