name = "Gravity Gun"
filename = "GravityGun-1.12.2-7.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2801/274/GravityGun-1.12.2-7.1.0.jar"
hash-format = "murmur2"
hash = "3380091461"

[update]
[update.curseforge]
file-id = 2801274
project-id = 229072
