name = "GunpowderLib"
filename = "GunpowderLib-1.12.2-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3168/863/GunpowderLib-1.12.2-1.1.jar"
hash-format = "murmur2"
hash = "752151041"

[update]
[update.curseforge]
file-id = 3168863
project-id = 356646
