name = "iChunUtil"
filename = "iChunUtil-1.12.2-7.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2801/262/iChunUtil-1.12.2-7.2.2.jar"
hash-format = "murmur2"
hash = "1712392953"

[update]
[update.curseforge]
file-id = 2801262
project-id = 229060
