name = "Just Enough Energistics (JEE)"
filename = "JustEnoughEnergistics-1.12.2-1.0.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2783/832/JustEnoughEnergistics-1.12.2-1.0.8.jar"
hash-format = "murmur2"
hash = "4241444590"

[update]
[update.curseforge]
file-id = 2783832
project-id = 310812
