name = "Large Ore Deposits"
filename = "AdLods-1.12.2-1.0.8.0-build.0504.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2961/524/AdLods-1.12.2-1.0.8.0-build.0504.jar"
hash-format = "murmur2"
hash = "2395712818"

[update]
[update.curseforge]
file-id = 2961524
project-id = 318833
