name = "Matter Overdrive: Community Edition"
filename = "MatterOverdrive-1.12.2-0.7.4-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3619/937/MatterOverdrive-1.12.2-0.7.4-universal.jar"
hash-format = "murmur2"
hash = "1378060761"

[update]
[update.curseforge]
file-id = 3619937
project-id = 557428
