name = "Sound Device Options"
filename = "moresoundconfig-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2707/92/moresoundconfig-1.0.4.jar"
hash-format = "murmur2"
hash = "1364153110"

[update]
[update.curseforge]
file-id = 2707092
project-id = 306555
