name = "MysticalLib"
filename = "mysticallib-1.12.2-1.13.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3483/816/mysticallib-1.12.2-1.13.0.jar"
hash-format = "murmur2"
hash = "293225086"

[update]
[update.curseforge]
file-id = 3483816
project-id = 277064
