name = "OnlinePictureFrame"
filename = "OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3047/154/OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar"
hash-format = "murmur2"
hash = "2002941006"

[update]
[update.curseforge]
file-id = 3047154
project-id = 257815
