name = "Project Red - Exploration"
filename = "ProjectRed-1.12.2-4.9.4.120-world.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2745/551/ProjectRed-1.12.2-4.9.4.120-world.jar"
hash-format = "murmur2"
hash = "2798396102"

[update]
[update.curseforge]
file-id = 2745551
project-id = 229049
