name = "Project Red - Compat"
filename = "ProjectRed-1.12.2-4.9.4.120-compat.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2745/546/ProjectRed-1.12.2-4.9.4.120-compat.jar"
hash-format = "murmur2"
hash = "473856560"

[update]
[update.curseforge]
file-id = 2745546
project-id = 229050
