name = "Project Red - Fabrication"
filename = "ProjectRed-1.12.2-4.9.4.120-fabrication.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2745/547/ProjectRed-1.12.2-4.9.4.120-fabrication.jar"
hash-format = "murmur2"
hash = "3501978731"

[update]
[update.curseforge]
file-id = 2745547
project-id = 230111
