name = "Project Red - Integration"
filename = "ProjectRed-1.12.2-4.9.4.120-integration.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2745/548/ProjectRed-1.12.2-4.9.4.120-integration.jar"
hash-format = "murmur2"
hash = "1782350993"

[update]
[update.curseforge]
file-id = 2745548
project-id = 229045
