name = "Thaumic Tinkerer"
filename = "thaumictinkerer-1.12.2-5.0-620a0c5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2957/213/thaumictinkerer-1.12.2-5.0-620a0c5.jar"
hash-format = "murmur2"
hash = "3105742345"

[update]
[update.curseforge]
file-id = 2957213
project-id = 75598
