name = "Thermal Solars"
filename = "thermalsolars-1.12.2-1.9.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2738/153/thermalsolars-1.12.2-1.9.5.jar"
hash-format = "murmur2"
hash = "2629675119"

[update]
[update.curseforge]
file-id = 2738153
project-id = 257381
