name = "Torchmaster"
filename = "torchmaster_1.12.2-1.8.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3529/742/torchmaster_1.12.2-1.8.5.0.jar"
hash-format = "murmur2"
hash = "614090222"

[update]
[update.curseforge]
file-id = 3529742
project-id = 254268
