name = "Unloader"
filename = "unloader-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2572/528/unloader-1.2.0.jar"
hash-format = "murmur2"
hash = "977612349"

[update]
[update.curseforge]
file-id = 2572528
project-id = 286230
