name = "Zetta Industries"
filename = "zettaindustries-1.3-1.12.2-161.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2636/576/zettaindustries-1.3-1.12.2-161.jar"
hash-format = "murmur2"
hash = "634885229"

[update]
[update.curseforge]
file-id = 2636576
project-id = 278475
